[package]
name = "snapshots"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.35"
notify = "7.0.0"
walkdir = "2.3"
blake3 = "1.5.4"
uuid = { version = "1.11.0", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.133"
